<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="89" errors="10" failures="3" skip="0"><testcase classname="api.tests.unittest.base_view_test.BaseViewTest" name="test_documentation" time="0.305"></testcase><testcase classname="api.tests.unittest.test_ancillary_seats.TestSeat" name="test_check_in_seat_info" time="3.440"></testcase><testcase classname="api.tests.unittest.test_common_models.SequenceTest" name="test_get_next_value" time="0.764"></testcase><testcase classname="api.tests.unittest.test_common_utils.CommonUtilsTest" name="test_failure" time="0.031"><failure type="builtins.AssertionError" message="0 != 1"><![CDATA[Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_common_utils.py", line 14, in test_failure
    self.assertEqual(0, 1)
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 814, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1
]]></failure></testcase><testcase classname="api.tests.unittest.test_common_utils.CommonUtilsTest" name="test_is_transaction_multi" time="0.034"></testcase><testcase classname="api.tests.unittest.test_covermore_main_api.CovermoreRequestTest" name="test_close_session" time="0.037"></testcase><testcase classname="api.tests.unittest.test_covermore_main_api.CovermoreRequestTest" name="test_create_session" time="0.053"></testcase><testcase classname="api.tests.unittest.test_covermore_main_api.CovermoreRequestTest" name="test_get_offer" time="0.038"></testcase><testcase classname="api.tests.unittest.test_covermore_main_api.CovermoreRequestTest" name="test_update_traveller" time="0.057"></testcase><testcase classname="api.tests.unittest.test_covermore_provider.CovermoreProviderTest" name="test_assign_insurance" time="1.463"></testcase><testcase classname="api.tests.unittest.test_credit_receivers.CreditReceiversTest" name="test_update_gocash_credit_with_correct_txn_id" time="0.977"><error type="builtins.AttributeError" message="module 'api.promotions.promo_code.signals' has no attribute 'pre_booking_offer_applied'"><![CDATA[Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/usr/local/python3/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_credit_receivers.py", line 26, in test_update_gocash_credit_with_correct_txn_id
    promo_code_signals.pre_booking_offer_applied.send(
AttributeError: module 'api.promotions.promo_code.signals' has no attribute 'pre_booking_offer_applied'
]]></error></testcase><testcase classname="api.tests.unittest.test_credit_receivers.CreditReceiversTest" name="test_update_gocash_credit_with_wrong_txn_id" time="0.742"><error type="builtins.AttributeError" message="module 'api.promotions.promo_code.signals' has no attribute 'pre_booking_offer_applied'"><![CDATA[Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/usr/local/python3/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_credit_receivers.py", line 20, in test_update_gocash_credit_with_wrong_txn_id
    promo_code_signals.pre_booking_offer_applied.send(sender=None, txn_id='SDFSDF')
AttributeError: module 'api.promotions.promo_code.signals' has no attribute 'pre_booking_offer_applied'
]]></error></testcase><testcase classname="api.tests.unittest.test_filo_main.FiloMainTest" name="test_get_header" time="0.031"></testcase><testcase classname="api.tests.unittest.test_filo_main.FiloMainTest" name="test_post" time="0.037"></testcase><testcase classname="api.tests.unittest.test_filo_main.FiloMainTest" name="test_redeem" time="0.063"></testcase><testcase classname="api.tests.unittest.test_flight_addon_utils.FlightAddonUtilsTest" name="test_deregister_farealert" time="1.311"></testcase><testcase classname="api.tests.unittest.test_flight_models.TestAncillaries" name="test_create_ancillary" time="1.791"></testcase><testcase classname="api.tests.unittest.test_flight_models.TestSeat" name="test_create_seat" time="0.846"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'paymentdetails' because they are referenced through a protected foreign key: 'Seat.paymentid'&quot;, &lt;QuerySet [&lt;Seat: Seat object (492)&gt;]&gt;)"><![CDATA[Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_flight_models.py", line 38, in tearDown
    self.payment_details.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'paymentdetails' because they are referenced through a protected foreign key: 'Seat.paymentid'", <QuerySet [<Seat: Seat object (492)>]>)
]]></error></testcase><testcase classname="api.tests.unittest.test_flight_utils.FlightUtils" name="test_fare_breakup_template" time="0.029"></testcase><testcase classname="api.tests.unittest.test_flight_utils.FlightUtils" name="test_get_base_fare_breakup" time="0.029"></testcase><testcase classname="api.tests.unittest.test_flight_utils.FlightUtils" name="test_get_discount_breakup" time="0.030"></testcase><testcase classname="api.tests.unittest.test_flight_utils.FlightUtils" name="test_get_fare" time="0.029"></testcase><testcase classname="api.tests.unittest.test_flight_utils.FlightUtils" name="test_get_farebreakup_v2" time="0.033"></testcase><testcase classname="api.tests.unittest.test_flight_utils.FlightUtils" name="test_get_fee_and_surcharge_breakup" time="0.028"></testcase><testcase classname="api.tests.unittest.test_flight_utils.FlightUtils" name="test_set_markup" time="0.029"></testcase><testcase classname="api.tests.unittest.test_gocash_api_router.GocashApiRouterTest" name="test_makeGetRequestGocash" time="0.057"></testcase><testcase classname="api.tests.unittest.test_goibibo_models.PaymentDetailsTest" name="test_is_travel_domestic" time="1.854"></testcase><testcase classname="api.tests.unittest.test_invoice.InvoiceTest" name="test_can_apply_invoice_info" time="0.961"></testcase><testcase classname="api.tests.unittest.test_invoice.InvoiceTest" name="test_generate_arn_number" time="1.164"></testcase><testcase classname="api.tests.unittest.test_invoice.InvoiceTest" name="test_generate_invoice_number" time="0.920"></testcase><testcase classname="api.tests.unittest.test_invoice.InvoiceTest" name="test_generate_number" time="0.710"></testcase><testcase classname="api.tests.unittest.test_invoice.InvoiceTest" name="test_get_arn_prefix" time="0.739"></testcase><testcase classname="api.tests.unittest.test_invoice.InvoiceTest" name="test_get_invoice_prefix" time="0.753"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_convenience_fee" time="0.049"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_convenience_fee_error_cases" time="0.044"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_data" time="0.032"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_final_airlines" time="0.035"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_final_suppliers" time="0.029"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_flavour" time="0.028"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_funnel" time="0.040"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_headers" time="0.029"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_traffic_medium" time="0.030"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_traffic_source" time="0.033"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_user_type" time="0.031"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_get_vertical" time="0.048"></testcase><testcase classname="api.tests.unittest.test_peshkash_api.PeshkashConvenienceFeeTest" name="test_post" time="0.046"></testcase><testcase classname="api.tests.unittest.test_promo_code_helpers.PromoCodeHelperTest" name="test_is_peshkash_promo_with_post_booking_offer" time="1.091"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'&quot;, &lt;QuerySet [&lt;PostBookingOffers: PostBookingOffers object (280)&gt;]&gt;)&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=0&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PostBookingOffersFactory.&lt;lambda&gt; at 0x7f4bea45c7b8&gt; for seq=0&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=1&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodeFactory.&lt;lambda&gt; at 0x7f4bea45c840&gt; for seq=0&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodePermFactory.&lt;lambda&gt; at 0x7f4bea476b70&gt; for seq=0&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_promo_code_helpers.py", line 77, in tearDown
    self.create_promo_1.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
("Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'", <QuerySet [<PostBookingOffers: PostBookingOffers object (280)>]>)
-------------------- >> begin captured logging << --------------------
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=0
factory.generate: DEBUG: Sequence: Computing next value of <function PostBookingOffersFactory.<lambda> at 0x7f4bea45c7b8> for seq=0
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=1
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodeFactory.<lambda> at 0x7f4bea45c840> for seq=0
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodePermFactory.<lambda> at 0x7f4bea476b70> for seq=0
--------------------- >> end captured logging << ---------------------]]></error></testcase><testcase classname="api.tests.unittest.test_promo_code_helpers.PromoCodeHelperTest" name="test_is_peshkash_promo_with_promo_code_in_peshkash_config" time="0.768"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'&quot;, &lt;QuerySet [&lt;PostBookingOffers: PostBookingOffers object (281)&gt;]&gt;)&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=2&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PostBookingOffersFactory.&lt;lambda&gt; at 0x7f4bea45c7b8&gt; for seq=1&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=3&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodeFactory.&lt;lambda&gt; at 0x7f4bea45c840&gt; for seq=1&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodePermFactory.&lt;lambda&gt; at 0x7f4bea476b70&gt; for seq=1&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_promo_code_helpers.py", line 77, in tearDown
    self.create_promo_1.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
("Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'", <QuerySet [<PostBookingOffers: PostBookingOffers object (281)>]>)
-------------------- >> begin captured logging << --------------------
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=2
factory.generate: DEBUG: Sequence: Computing next value of <function PostBookingOffersFactory.<lambda> at 0x7f4bea45c7b8> for seq=1
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=3
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodeFactory.<lambda> at 0x7f4bea45c840> for seq=1
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodePermFactory.<lambda> at 0x7f4bea476b70> for seq=1
--------------------- >> end captured logging << ---------------------]]></error></testcase><testcase classname="api.tests.unittest.test_promo_code_helpers.PromoCodeHelperTest" name="test_is_promo_code_combined_offer_with_right_promo_code_and_combined_offer" time="0.953"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'&quot;, &lt;QuerySet [&lt;PostBookingOffers: PostBookingOffers object (282)&gt;]&gt;)&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=4&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PostBookingOffersFactory.&lt;lambda&gt; at 0x7f4bea45c7b8&gt; for seq=2&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=5&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodeFactory.&lt;lambda&gt; at 0x7f4bea45c840&gt; for seq=2&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodePermFactory.&lt;lambda&gt; at 0x7f4bea476b70&gt; for seq=2&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_promo_code_helpers.py", line 77, in tearDown
    self.create_promo_1.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
("Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'", <QuerySet [<PostBookingOffers: PostBookingOffers object (282)>]>)
-------------------- >> begin captured logging << --------------------
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=4
factory.generate: DEBUG: Sequence: Computing next value of <function PostBookingOffersFactory.<lambda> at 0x7f4bea45c7b8> for seq=2
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=5
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodeFactory.<lambda> at 0x7f4bea45c840> for seq=2
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodePermFactory.<lambda> at 0x7f4bea476b70> for seq=2
--------------------- >> end captured logging << ---------------------]]></error></testcase><testcase classname="api.tests.unittest.test_promo_code_helpers.PromoCodeHelperTest" name="test_is_promo_code_combined_offer_with_right_promo_code_but_gocash_info" time="0.704"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'&quot;, &lt;QuerySet [&lt;PostBookingOffers: PostBookingOffers object (283)&gt;]&gt;)&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=6&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PostBookingOffersFactory.&lt;lambda&gt; at 0x7f4bea45c7b8&gt; for seq=3&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=7&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodeFactory.&lt;lambda&gt; at 0x7f4bea45c840&gt; for seq=3&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodePermFactory.&lt;lambda&gt; at 0x7f4bea476b70&gt; for seq=3&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_promo_code_helpers.py", line 77, in tearDown
    self.create_promo_1.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
("Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'", <QuerySet [<PostBookingOffers: PostBookingOffers object (283)>]>)
-------------------- >> begin captured logging << --------------------
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=6
factory.generate: DEBUG: Sequence: Computing next value of <function PostBookingOffersFactory.<lambda> at 0x7f4bea45c7b8> for seq=3
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=7
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodeFactory.<lambda> at 0x7f4bea45c840> for seq=3
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodePermFactory.<lambda> at 0x7f4bea476b70> for seq=3
--------------------- >> end captured logging << ---------------------]]></error></testcase><testcase classname="api.tests.unittest.test_promo_code_helpers.PromoCodeHelperTest" name="test_is_promo_code_combined_offer_with_right_promo_code_but_not_combined_offer" time="0.783"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'&quot;, &lt;QuerySet [&lt;PostBookingOffers: PostBookingOffers object (284)&gt;]&gt;)&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=8&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PostBookingOffersFactory.&lt;lambda&gt; at 0x7f4bea45c7b8&gt; for seq=4&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=9&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodeFactory.&lt;lambda&gt; at 0x7f4bea45c840&gt; for seq=4&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodePermFactory.&lt;lambda&gt; at 0x7f4bea476b70&gt; for seq=4&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_promo_code_helpers.py", line 77, in tearDown
    self.create_promo_1.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
("Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'", <QuerySet [<PostBookingOffers: PostBookingOffers object (284)>]>)
-------------------- >> begin captured logging << --------------------
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=8
factory.generate: DEBUG: Sequence: Computing next value of <function PostBookingOffersFactory.<lambda> at 0x7f4bea45c7b8> for seq=4
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=9
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodeFactory.<lambda> at 0x7f4bea45c840> for seq=4
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodePermFactory.<lambda> at 0x7f4bea476b70> for seq=4
--------------------- >> end captured logging << ---------------------]]></error></testcase><testcase classname="api.tests.unittest.test_promo_code_helpers.PromoCodeHelperTest" name="test_is_promo_code_combined_offer_with_wrong_promo_code" time="0.682"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'&quot;, &lt;QuerySet [&lt;PostBookingOffers: PostBookingOffers object (285)&gt;]&gt;)&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=10&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PostBookingOffersFactory.&lt;lambda&gt; at 0x7f4bea45c7b8&gt; for seq=5&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=11&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodeFactory.&lt;lambda&gt; at 0x7f4bea45c840&gt; for seq=5&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodePermFactory.&lt;lambda&gt; at 0x7f4bea476b70&gt; for seq=5&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_promo_code_helpers.py", line 77, in tearDown
    self.create_promo_1.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
("Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'", <QuerySet [<PostBookingOffers: PostBookingOffers object (285)>]>)
-------------------- >> begin captured logging << --------------------
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=10
factory.generate: DEBUG: Sequence: Computing next value of <function PostBookingOffersFactory.<lambda> at 0x7f4bea45c7b8> for seq=5
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=11
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodeFactory.<lambda> at 0x7f4bea45c840> for seq=5
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodePermFactory.<lambda> at 0x7f4bea476b70> for seq=5
--------------------- >> end captured logging << ---------------------]]></error></testcase><testcase classname="api.tests.unittest.test_promo_code_helpers.PromoCodeHelperTest" name="test_is_promo_in_peshkash_config" time="0.647"><error type="django.db.models.deletion.ProtectedError" message="(&quot;Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'&quot;, &lt;QuerySet [&lt;PostBookingOffers: PostBookingOffers object (286)&gt;]&gt;)&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=12&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PostBookingOffersFactory.&lt;lambda&gt; at 0x7f4bea45c7b8&gt; for seq=6&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function CreatePromoFactory.&lt;lambda&gt; at 0x7f4bea45c9d8&gt; for seq=13&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodeFactory.&lt;lambda&gt; at 0x7f4bea45c840&gt; for seq=6&#10;factory.generate: DEBUG: Sequence: Computing next value of &lt;function PromoCodePermFactory.&lt;lambda&gt; at 0x7f4bea476b70&gt; for seq=6&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 604, in run
    self.tearDown()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_promo_code_helpers.py", line 77, in tearDown
    self.create_promo_1.delete()
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 878, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
("Cannot delete some instances of model 'createpromo' because they are referenced through a protected foreign key: 'PostBookingOffers.codecreatename'", <QuerySet [<PostBookingOffers: PostBookingOffers object (286)>]>)
-------------------- >> begin captured logging << --------------------
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=12
factory.generate: DEBUG: Sequence: Computing next value of <function PostBookingOffersFactory.<lambda> at 0x7f4bea45c7b8> for seq=6
factory.generate: DEBUG: Sequence: Computing next value of <function CreatePromoFactory.<lambda> at 0x7f4bea45c9d8> for seq=13
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodeFactory.<lambda> at 0x7f4bea45c840> for seq=6
factory.generate: DEBUG: Sequence: Computing next value of <function PromoCodePermFactory.<lambda> at 0x7f4bea476b70> for seq=6
--------------------- >> end captured logging << ---------------------]]></error></testcase><testcase classname="api.tests.unittest.test_promotion_factory.PromotionFactoryTest" name="test_get_code_type_factory_with_invalid_type" time="0.039"></testcase><testcase classname="api.tests.unittest.test_promotion_factory.PromotionFactoryTest" name="test_get_code_type_factory_with_valid_type" time="0.030"></testcase><testcase classname="api.tests.unittest.test_ticketing.TestTicketingProfiler" name="test_get_credit_card_info" time="4.612"><failure type="builtins.AssertionError" message="{} != {'Status': 'Active1', 'status': 'success',[190 chars] '9'}&#10;- {}&#10;+ {'HierarchyLevelID': '297420',&#10;+  'Key': '210359',&#10;+  'Name': 'IBIBO',&#10;+  'ProfileID': '22995025',&#10;+  'ProfileType': 'Account',&#10;+  'Status': 'Active1',&#10;+  'TemplateID': '5805',&#10;+  'TemplateVersion': '9',&#10;+  'Type': 'CRECRD',&#10;+  'Version': '0',&#10;+  'status': 'success'}"><![CDATA[Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_ticketing.py", line 181, in test_get_credit_card_info
    self.assertEqual(resp, simplejson.loads(self.gds_profile1.profile_info_json))
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 1112, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 666, in fail
    raise self.failureException(msg)
AssertionError: {} != {'Status': 'Active1', 'status': 'success',[190 chars] '9'}
- {}
+ {'HierarchyLevelID': '297420',
+  'Key': '210359',
+  'Name': 'IBIBO',
+  'ProfileID': '22995025',
+  'ProfileType': 'Account',
+  'Status': 'Active1',
+  'TemplateID': '5805',
+  'TemplateVersion': '9',
+  'Type': 'CRECRD',
+  'Version': '0',
+  'status': 'success'}
]]></failure></testcase><testcase classname="api.tests.unittest.test_ticketing.TestTicketingProfiler" name="test_get_office_id" time="3.982"><failure type="builtins.AssertionError" message="'' != 'office7'&#10;+ office7"><![CDATA[Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/usr/local/python3/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/usr/local/goibibo/hulk/api/tests/unittest/test_ticketing.py", line 129, in test_get_office_id
    self.assertEqual(resp[0], 'office7')
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 1194, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/python3/lib/python3.6/unittest/case.py", line 666, in fail
    raise self.failureException(msg)
AssertionError: '' != 'office7'
+ office7
]]></failure></testcase><testcase classname="api.tests.unittest.test_tier_benefits_helper.TestTierBenefitsHelper" name="test_get_benefits" time="0.032"></testcase><testcase classname="api.tests.unittest.test_tier_benefits_helper.TestTierBenefitsHelper" name="test_is_benefits_applicable" time="0.032"></testcase><testcase classname="api.tests.unittest.test_tier_benefits_helper.TestTierBenefitsHelper" name="test_on_booking_redeem_benefits" time="0.030"></testcase><testcase classname="api.tests.unittest.test_tier_benefits_helper.TestTierBenefitsHelper" name="test_reset_usage" time="0.029"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_booking_class" time="0.032"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_carrier" time="0.032"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_destination" time="0.029"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_flight_path_mapping" time="0.091"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_no_of_passenders" time="0.030"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_onward_flights_info" time="0.031"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_origin" time="0.030"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_passengers_info" time="0.028"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_return_flights_info" time="0.029"></testcase><testcase classname="api.tests.unittest.test_tour_code.FlightInfoParserTest" name="test_get_unique_stops" time="0.035"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_bookingclass" time="0.030"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_carrierid" time="0.030"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_connecting_source_and_dest" time="0.029"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_dept_date_end" time="0.030"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_dept_date_start" time="0.032"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_dest_country_code" time="0.054"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_destination" time="0.031"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_farebasis" time="0.033"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_flight_number" time="0.036"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_no_of_pax" time="0.031"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_no_of_stops" time="0.032"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_source" time="0.029"></testcase><testcase classname="api.tests.unittest.test_tour_code.TourCodeParamParserTest" name="test_process_source_country_code" time="0.028"></testcase><testcase classname="api.tests.unittest.test_voyager.TestVoyager" name="test_country_code_from_airport_code_with_error_cases" time="0.121"></testcase><testcase classname="api.tests.unittest.test_voyager.TestVoyager" name="test_get_country_code_from_airport_code" time="0.039"></testcase><testcase classname="api.tests.unittest.test_voyager_main.TestVoyagerApi" name="test_find_node_by_name_v2" time="0.058"></testcase><testcase classname="api.tests.unittest.test_voyager_main.TestVoyagerApi" name="test_get" time="0.041"></testcase><testcase classname="api.tests.unittest.test_voyager_main.TestVoyagerApi" name="test_get_header" time="0.030"></testcase></testsuite>